{% set name = "deepspeed" %}
{% set version = "0.11.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/microsoft/DeepSpeed 
  git_rev: v{{ version }}

build:
  number: 1
  string: cuda{{ cudatoolkit | replace(".*", "") }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}
  script: DS_BUILD_OPS=1; DS_BUILD_FUSED_LAMB=0; DS_BUILD_EVOFORMER_ATTN=0; DS_BUILD_CUTLASS_OPS=0; DS_BUILD_RAGGED_DEVICE_OPS=0; DS_BUILD_AIO=0; {{ PYTHON }} -m pip install deepspeed=={{ version }} --no-deps --ignore-installed --no-cache-dir -vvv
  script_env:
    - CUDA_HOME
  
requirements:
  build:
    - {{ compiler('c') }}
    - python            {{ python }}
    - pytorch           {{ pytorch }}
  host:
    - pip
    - pytorch           {{ pytorch }}
    - python            {{ python }}
    - libaio  # [linux]
  run:
    - hjson-py
    - ninja             {{ ninja }}
    - numpy             {{ numpy }}
    - packaging>=20.0
    - psutil            {{ psutil }}
    - python            {{ python }}
    - py-cpuinfo
    - pydantic          {{ pydantic }}
    - tqdm              {{ tqdm }}
    - pytorch           {{ pytorch }}

about:
  home: https://github.com/microsoft/DeepSpeed.git 
  license: MIT
  license_file: LICENSE
  summary: 'DeepSpeed Library: An easy-to-use deep learning optimization software suite.'
  description: 'DeepSpeed Library: An easy-to-use deep learning optimization software suite.'
  doc_url: https://deepspeed.readthedocs.io/
  dev_url: https://github.com/microsoft/DeepSpeed.git

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
